version: '3'

services:

  mlc-accounting-mongo:
    image: mongo:latest
    container_name: mlc-accounting-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mlc-accounting-mongo-express:
    image: mongo-express:latest
    container_name: mlc-accounting-mongo-express
    restart: always
    ports:
      - 8017:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mlc-accounting-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example