version: '3'

services:

  mlc-accounting-mongo:
    image: mongo:latest
    container_name: mlc-accounting-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mlc-accounting-mongo-express:
    image: mongo-express:latest
    container_name: mlc-accounting-mongo-express
    restart: always
    ports:
      - 8017:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mlc-accounting-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mlc-accounting-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: mlc-accounting-zookeeper
    restart: always
    ports:
        - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  mlc-accounting-kafka:
    image: confluentinc/cp-kafka:latest
    container_name: mlc-accounting-kafka
    restart: always
    depends_on:
      - mlc-accounting-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'mlc-accounting-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://mlc-accounting-kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mlc-accounting-referential:
    image: mlc-accounting-referential:latest
    build: ./Sources/Referential/Api/Dockerfile
    container_name: mlc-accounting-referential
    restart: always
    ports:
      - "5080:5080"
      - "5081:5081"
    environment:
      - ASPNETCORE_URLS=http://+:5080;http://+:5081
      - ASPNETCORE_HTTP_PORT=5080
      - MANAGEMENT_HTTP_PORT=5081
      - ASPNETCORE_ENVIRONMENT=Docker

  mlc-accounting-integration:
    image: mlc-accounting-integration:latest
    build: ./Sources/Integration/Api/Dockerfile
    container_name: mlc-accounting-integration
    restart: always
    ports:
      - "5082:5082"
      - "5083:5083"
    environment:
      - ASPNETCORE_URLS=http://+:5082;http://+:5083
      - ASPNETCORE_HTTP_PORT=5082
      - MANAGEMENT_HTTP_PORT=5083
      - ASPNETCORE_ENVIRONMENT=Docker